### ISSUE TITLE
Sorting by price<->range ratio

### ISSUE THREAD

**Issue by benediktvaldez** [hugihlynsson/veldu-rafbil#89]
Would be interesting to be able to sort the cars by „how much range am I getting for the price I'm paying”

Might be out of scope in your opinion, just something I consider sometimes as one of the factors when looking at EVs.

**Comment by hugihlynsson** [comment]
I love it! I actually haven't just contemplated this but already implemented in the used cars with the hidden sorting query parameter "virdi": https://veldurafbil.is/notadir?radaeftir=virdi

For all the other sorting options, the values that are being sorted on are already being displayed (the name, price, range and acceleration). The challenge for something like km/price is that I'd want to display the value for each item and I have to figure out how I would be able to fit that into the designs.

I'm going to keep this issue open to make sure that I don't forget about this popular request!

**Comment by hugihlynsson** [comment]
I've shipped an iteration of this that allows the use of the `virdi` query parameter on new cars like this: https://veldurafbil.is/?radaeftir=virdi. See 6fbe029 for details. Now we just need to solve how we might make this visible to users and then we can add this to the sorting UI!

**Comment by hugihlynsson** [comment]
Allright, I've implemented something in #92. Here is the build from that PR: https://veldu-rafbil-git-display-sorting-by-value.hugihlynsson.vercel.app
I'd love to hear your thoughts on the UI @benediktvaldez 🤙

**Comment by hugihlynsson** [comment]
I've merged the branch and it's shipped to https://veldurafbil.is 🎉 I'm closing the issue but if you have any feedback don't hesitate to leave it here.
