### ISSUE TITLE
Filter display bug

### ISSUE THREAD

**Issue by hakong** [hugihlynsson/veldu-rafbil#902]
Filtering by `Framboð: Fáanlegir` results in 

```
154 bílar passa við:
Framboð: Væntanlegir
```
And the URL updating to https://veldurafbil.is/?frambod=vaentanlegir

The filter works and only shows what's available but displays "Vænganlegir".
![veldurafbil_filter](https://github.com/hugihlynsson/veldu-rafbil/assets/4422113/925172db-c944-4c78-b78d-214cd7461651)

Filtering by "Vænganlegir" works fine.

**Comment by hugihlynsson** [comment]
I just shipped https://github.com/hugihlynsson/veldu-rafbil/commit/61c1cf66e43d20320ae7c735ad54812875438f5d that fixes this issue! It looks like I had the wrong key for this single specific filter value causing it to do the correct filtering (coincidentally) but writing the wrong filter to the query, causing it to filter wrong on a page re-load. You should be able to correctly filter _Available_ cars now at https://veldurafbil.is. Thanks_ again for reporting!
